name: Deploy Express API to DigitalOcean

# This workflow triggers when a new release is published
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest # The type of machine to run the job on

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Step to create the .env file from GitHub Secrets
      - name: Create .env file
        run: |
          echo "DB_CONN_STRING=${{ secrets.DB_CONN_STRING }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
          echo "EXTERNAL_API_BASE_URL=${{ secrets.EXTERNAL_API_BASE_URL }}" >> .env

      - name: Copy project files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/var/www/api"
          overwrite: true

      # This action runs the commands on your server to restart the app.
      - name: Restart application on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Source nvm to make node, npm, and pm2 available
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # Navigate to the application directory
            cd /var/www/api
            
            # Install only production dependencies on the server
            # This is faster than copying node_modules from the runner
            npm install

            npm run build
            
            # Restart the app using the ecosystem file
            pm2 startOrRestart ecosystem.config.js --env production